### ISSUE TITLE
Suitable AVR chips?

### ISSUE THREAD

**Issue by clickworkorange** [mbs38/yaMBSiavr#1]
Thanks for making this library available, looks very good! Do you think it would run on the ATtiny841? 

http://www.atmel.com/Images/Atmel-8495-8-bit-AVR-Microcontrollers-ATtiny441-ATtiny841_Datasheet.pdf

**Comment by mbs38** [comment]
You're welcome. You will have to add another section of defines to the header file yaMBSiavr.h - other than that I don't see any problems running the lib on the tinyX41 series controllers.

**Comment by clickworkorange** [comment]
Brilliant, many thanks!
