### ISSUE TITLE
Cant get value from slave on each request

### ISSUE THREAD

**Issue by abhisekmanna** [mbs38/yaMBSiavr#16]
Hi, 
Thanks for the library. 
I am using Atmega1284p as master. My baud rate is 9600, f_cpu set on 8mhz. I want to read holding registers of my rtu slave device. I was able to get data from slave after 15-20 times request on loop and after that I am getting response. I want to get response data from slave whenever I request for data from slave. What should be clock timer? Please help.

**Comment by mbs38** [comment]
Hi, you're welcome.

Without having seen your code I can't help.

Also, as stated in the master-example.c, the library is meant to be used as slave device only (hence the name). Maybe some changes in the last two years have broken the hacky usage as a master. Fixing that though has zero priority for me atm.

Best,
Max

**Comment by mbs38** [comment]
Can't confirm this atm.
