### ISSUE TITLE
Trying to compile

### ISSUE THREAD

**Issue by Gaitashaper** [mbs38/yaMBSiavr#17]
Thank you very much for your code, is a interesting work!!

I am trying to compile the example code but I can not doing, I have a lot of error during compiling process.

I am using AVR Studio 6 and example code same as posted here

What compiling software you are using?

Thank you very much in advance

**Comment by mbs38** [comment]
Hi, 
I am using makefiles + avr-gcc.

What errors do you get?

Best,
Max

**Comment by Gaitashaper** [comment]
Hi Max, thanks for your answer. Next the image of AVR Studio Errors. I hope you can help me. Thank you very much in advance.

![error modbus](https://user-images.githubusercontent.com/8293970/132361684-9d7c0e9d-be62-4244-97db-abbd5b8c0ccf.jpeg)

**Comment by mbs38** [comment]
Hi,
AVR Studio seems to be a little more pedantic and I have forgotten to put an "extern" in front of the definitions of DataPos and rxbuffer within the header file. I've pushed a fix (ea26b7b). Hope this fixes the issue for you.

Best,
Max

**Comment by Gaitashaper** [comment]
Hi Max, thanks for your answer and cooperation. Now, that is a situation........ What do you think about?

![modbus error](https://user-images.githubusercontent.com/8293970/132385995-d192d657-d1cf-4ac9-9e34-d3cb84977058.jpg)

**Comment by mbs38** [comment]
Looks like yaMBSiavr.c is loaded in multiple places. Did you change the example.c in any way?

**Comment by Gaitashaper** [comment]
Hi Max, I was able to compile the program with the extern added. I was making a mistake during compilation. The program is ok and compiling well in AVR Studio. Today I am goin to test it on the hardware. Thank you very much for your answer, support and cooperation. Sebastián.

**Comment by mbs38** [comment]
Good to hear that you have been able to resolve the issues you had been experiencing. 
You're welcome.
Max
