### ISSUE TITLE
Direction signal too short

### ISSUE THREAD

**Issue by clickworkorange** [mbs38/yaMBSiavr#21]
Thank you for this nice little library! I've built [a simple RTU](https://github.com/clickworkorange/AVR-PWM-RTU) using a plain ATMega328 (non-P/PU/PB) running at 8MHz which receives commands correctly, but the replies are being truncated due to some kind of timing issue with the direction pin. 

![Screenshot_2023-12-27_14-53-45](https://github.com/mbs38/yaMBSiavr/assets/196348/9b7b57dc-66a9-4f62-b090-a4a46b0d9d70)
Here I captured the RTU response on ATMega pin 3 when setting register 4 to 0. Looks correct to me, despite the PicoScope decoder complaining about start & end. 

![Screenshot_2023-12-27_15-09-30](https://github.com/mbs38/yaMBSiavr/assets/196348/1c3b8163-e5c4-47df-b034-101881623e7a)
Here I captured RTU response from MAX485 output on channel A (blue) and direction signal from ATMega pin 4 on channel B (red). The direction signal is much too short (exactly 50us) which truncates the response. The master is Python MinimalModbus which throws the error 

`minimalmodbus.InvalidResponseError: Too short Modbus RTU response (minimum length 4 bytes). Response: 'ÿ' `

Any ideas?

**Comment by mbs38** [comment]
Hi,
the timing of the UART should be fine when using an 8 MHz crystal (0.2 % error). I would recommend using a baud rate crystal though (like 7.3728 MHz). I usually go for the highest frequency baud rate crystal possible. With the 328p @ 5V I would go for 18.432 MHz.

About your issue:

You're probably switching the enable pin off in every loop with line 93:
![image](https://github.com/mbs38/yaMBSiavr/assets/16289545/60f6855e-35f1-40e9-b2c0-b09adbf08a28)

Also: When fixing that keep in mind that an operation like PORTD|= ... can be interrupted and if the ISR also accesses PORTD (like the ISRs in the modbus library do!) you will get into terrible trouble.

**Comment by clickworkorange** [comment]
Ah. Thank you! I forgot I was forcing the ports in the setLevel function, that's rather crude. But it shouldn't be called in the main loop, only when a button is pressed or when function code 10 is received. Perhaps that's what you meant. I had only been testing the Modbus communication by doing just that, and since FC 10 loops through the available channels it will drop into case 2 and reset the enable pin. I guess the 50us delay before it going low was spent dealing with cases 0 and 1... Doh! I can confirm that function code 3 (read multiple registers) works flawlessly - if only I had tested that I might have found the issue on my own (note to self: try more than one thing next time). 

I'm not sure I understand what you mean with the comment about port assignments being interruptible, I always thought these were ~~monolithic~~ atomic - as in the byte being transferred to the port in a single step. Do you mean it might get half way through setting the port value before getting interrupted? That would indeed cause some major head scratching - particularly for a novice like me! Begs the question - though I know this is not the best place for it - how _should_ I go about setting pins on a port which has some pins controlled in an ISR? 

Edit: The answer might be as simple as disabling interrupts at the top of the function, and re-enabling them at the end.

**Comment by clickworkorange** [comment]
Closing this since it was a wetware error unrelated to yaMBSiavr - with thanks to @mbs38 for clearing it up!

**Comment by mbs38** [comment]
You're welcome. 

> Edit: The answer might be as simple as disabling interrupts at the top of the function, and re-enabling them at the end.

Then you will lose interrupts in that time. But the thought is not bad at all. 

```
#include <util/atomic.h>
...
...
ATOMIC_BLOCK(ATOMIC_FORCEON) {
    PORTD|=0x01;
}
```

That is all you need.
