### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by akshulg** [mbs38/yaMBSiavr#4]
How to use the library and example code to make hex file for Atmega16 (or any) microcontroller. I copy the code of example.c in Atmel Studios and copy the .h file in include folder in WinAVR. But when I build the code the error shows- "yaMBSiavr.h" No such directory found.

**Comment by mwue** [comment]
You have to copy all files together in your project folder, yaMVSiavr.[c,h] and example.c too.

**Comment by mwue** [comment]
btw. ... the atmega16 mcu is not supported by the code. Read and modify yaMBSiavr.h to make it work for this mcu. e.g.  mega8 , mega168 , tiny4313 (and some more) are supported yet.

**Comment by akshulg** [comment]
But atmega16 is also defined in .h file!

**Comment by drdbrr** [comment]
You must modify timer function and interrupt.02.12.2017, 09:22, "Akshul Goyal" <notifications@github.com>:But atmega16 is also defined in .h file!

**Comment by mbs38** [comment]
I suppose that this has already been resolved?
