### ISSUE TITLE
Definition for ATtiny102

### ISSUE THREAD

**Issue by BullT** [mbs38/yaMBSiavr#7]
Hi,

I'm new with the Atmel Studio and with AVR family. I'm traying to use your library with an ATtiny102 working at 8Mhz or at 12MHz.
I have some concern about how define the ATiny102 on the yaMBSiavr.h file.

Can you give me a hand to do this?

Thanks
BullT

**Comment by mbs38** [comment]
Hi,
the ATtiny102 does not have enough flash. You will have to use another controller.

Best,
Max
