### ISSUE TITLE
Hi! Thank for yor lib .I use atmega16, it work nice when i use proteus to simulate but cant work in real curcuit. Can you help me resolve this problem 

### ISSUE THREAD

**Issue by sooley** [mbs38/yaMBSiavr#9]

**Comment by mbs38** [comment]
Hi, there is no way I can help with this little information. Seems like you are a beginner so check the basic stuff: supply voltages, shorts, fuse settings, choice of crystal...

Best,
Max

**Comment by mbs38** [comment]
Not an issue.

**Comment by sooley** [comment]
Oke thank u may be im wrong in fulse setting



Vào 2:18 Th 3, 10 thg 9 2019 Max B. <notifications@github.com> đã viết:
